echo -ne "unknown         -10PEHVPSBD          TATTCT                         6  S000392\t"; grep -P "TATTCT|AGAATA" $1 | wc -l
echo -ne "unknown         -141NTG13            GCTTTTGATGACTTCAAACAC          21 S000335\t"; grep -P "GCTTTTGATGACTTCAAACAC|GTGTTTGAAGTCATCAAAAGC" $1 | wc -l
echo -ne "unknown         -284MOTIFZMSBE1      CGTGCAAGCCCAAAGGCCAATCGGCCCAGA 30 S000285\t"; grep -P "CGTGCAAGCCCAAAGGCCAATCGGCCCAGA|TCTGGGCCGATTGGCCTTTGGGCTTGCACG" $1 | wc -l
echo -ne "unknown         -300CORE             TGTAAAG                        7  S000001\t"; grep -P "TGTAAAG|CTTTACA" $1 | wc -l
echo -ne "unknown         -300ELEMENT          TGHAAARK                       8  S000122\t"; grep -P "TG[ATC]AAA[AG][GT]|[AC][CT]TTT[GAT]CA" $1 | wc -l
echo -ne "unknown         -300MOTIFZMZEIN      RTGAGTCAT                      9  S000002\t"; grep -P "[AG]TGAGTCAT|ATGACTCA[CT]" $1 | wc -l
echo -ne "unknown         -314MOTIFZMSBE1      ACATAAAATAAAAAAAGGCA           20 S000284\t"; grep -P "ACATAAAATAAAAAAAGGCA|TGCCTTTTTTTATTTTATGT" $1 | wc -l
echo -ne "unknown         14BPATERD1           CACTAAATTGTCAC                 14 S000412\t"; grep -P "CACTAAATTGTCAC|GTGACAATTTAGTG" $1 | wc -l
echo -ne "unknown         20NTNTNOS            TGAGCTAAGCACATACGTCA           20 S000312\t"; grep -P "TGAGCTAAGCACATACGTCA|TGACGTATGTGCTTAGCTCA" $1 | wc -l
echo -ne "unknown         23BPUASNSCYCB1       TTTATTTACCAAACGGTAACATC        23 S000283\t"; grep -P "TTTATTTACCAAACGGTAACATC|GATGTTACCGTTTGGTAAATAAA" $1 | wc -l
echo -ne "unknown         23BPZM27KDAZEIN      GACGTGTAAAGTAAATTTACAAC        23 S000341\t"; grep -P "GACGTGTAAAGTAAATTTACAAC|GTTGTAAATTTACTTTACACGTC" $1 | wc -l
echo -ne "unknown         27BPDRCONSENSUSPS25S TCCGCCWCTTGTATTCGTTGCGTTGMA    27 S000286\t"; grep -P "TCCGCC[AT]CTTGTATTCGTTGCGTTG[AC]A|T[GT]CAACGCAACGAATACAAG[AT]GGCGGA" $1 | wc -l
echo -ne "unknown         2SSEEDPROTBANAPA     CAAACAC                        7  S000143\t"; grep -P "CAAACAC|GTGTTTG" $1 | wc -l
echo -ne "unknown         3AF1BOXPSRBCS3       AAATAGATAAATAAAAACATT          21 S000004\t"; grep -P "AAATAGATAAATAAAAACATT|AATGTTTTTATTTATCTATTT" $1 | wc -l
echo -ne "unknown         5256BOXLELAT5256     TGTGGTTATATA                   12 S000279\t"; grep -P "TGTGGTTATATA|TATATAACCACA" $1 | wc -l
echo -ne "unknown         5659BOXLELAT5659     GAAWTTGTGA                     10 S000280\t"; grep -P "GAA[AT]TTGTGA|TCACAA[AT]TTC" $1 | wc -l
echo -ne "unknown         AACACOREOSGLUB1      AACAAAC                        7  S000353\t"; grep -P "AACAAAC|GTTTGTT" $1 | wc -l
echo -ne "unknown         AACAOSGLUB1          CAACAAACTATATC                 14 S000276\t"; grep -P "CAACAAACTATATC|GATATAGTTTGTTG" $1 | wc -l
echo -ne "unknown         AAGACGTAGATACL12     AAGACGTAG                      9  S000344\t"; grep -P "AAGACGTAG|CTACGTCTT" $1 | wc -l
echo -ne "unknown         ABADESI1             RTACGTGGCR                     10 S000007\t"; grep -P "[AG]TACGTGGCR|RGCCACGTA[CT]" $1 | wc -l
echo -ne "unknown         ABADESI2             GGACGCGTGGC                    11 S000008\t"; grep -P "GGACGCGTGGC|GCCACGCGTCC" $1 | wc -l
echo -ne "unknown         ABAREG2              ATGTACGAAGC                    11 S000009\t"; grep -P "ATGTACGAAGC|GCTTCGTACAT" $1 | wc -l
echo -ne "unknown         ABASEED1             TGTTACGTGCC                    11 S000011\t"; grep -P "TGTTACGTGCC|GGCACGTAACA" $1 | wc -l
echo -ne "unknown         ABFOS                GCATCTTTACTTTAGCATC            19 S000190\t"; grep -P "GCATCTTTACTTTAGCATC|GATGCTAAAGTAAAGATGC" $1 | wc -l
echo -ne "unknown         ABRE2HVA1            CCTACGTGGCGG                   12 S000134\t"; grep -P "CCTACGTGGCGG|CCGCCACGTAGG" $1 | wc -l
echo -ne "unknown         ABRE2HVA22           CGCACGTGTC                     10 S000117\t"; grep -P "CGCACGTGTC|GACACGTGCG" $1 | wc -l
echo -ne "unknown         ABRE3HVA1            GCAACGTGTC                     10 S000135\t"; grep -P "GCAACGTGTC|GACACGTTGC" $1 | wc -l
echo -ne "unknown         ABRE3HVA22           GCCACGTACA                     10 S000118\t"; grep -P "GCCACGTACA|TGTACGTGGC" $1 | wc -l
echo -ne "unknown         ABRE3OSRAB16         GTACGTGGCGC                    11 S000120\t"; grep -P "GTACGTGGCGC|GCGCCACGTAC" $1 | wc -l
echo -ne "unknown         ABREA2HVA1           CCTACGTGGC                     10 S000140\t"; grep -P "CCTACGTGGC|GCCACGTAGG" $1 | wc -l
echo -ne "unknown         ABREATCONSENSUS      YACGTGGC                       8  S000406\t"; grep -P "[CT]ACGTGGC|GCCACGT[AG]" $1 | wc -l
echo -ne "unknown         ABREATRD22           RYACGTGGYR                     10 S000013\t"; grep -P "[AG][CT]ACGTGGYR|RYCCACGT[AG][CT]" $1 | wc -l
echo -ne "unknown         ABREAZMRAB28         GCCACGTGGG                     10 S000218\t"; grep -P "GCCACGTGGG|CCCACGTGGC" $1 | wc -l
echo -ne "unknown         ABREBNNAPA           CGCCACGTGTCC                   12 S000145\t"; grep -P "CGCCACGTGTCC|GGACACGTGGCG" $1 | wc -l
echo -ne "unknown         ABREBZMRAB28         TCCACGTCTC                     10 S000219\t"; grep -P "TCCACGTCTC|GAGACGTGGA" $1 | wc -l
echo -ne "unknown         ABRECE1HVA22         TGCCACCGG                      9  S000014\t"; grep -P "TGCCACCGG|CCGGTGGCA" $1 | wc -l
echo -ne "unknown         ABRECE3HVA1          ACGCGTGTCCTC                   12 S000141\t"; grep -P "ACGCGTGTCCTC|GAGGACACGCGT" $1 | wc -l
echo -ne "unknown         ABRECE3ZMRAB28       ACGCGCCTCCTC                   12 S000221\t"; grep -P "ACGCGCCTCCTC|GAGGAGGCGCGT" $1 | wc -l
echo -ne "unknown         ABREDISTBBNNAPA      GCCACTTGTC                     10 S000262\t"; grep -P "GCCACTTGTC|GACAAGTGGC" $1 | wc -l
echo -ne "unknown         ABRELATERD1          ACGTG                          5  S000414\t"; grep -P "ACGTG|CACGT" $1 | wc -l
echo -ne "unknown         ABREMOTIFAOSOSEM     TACGTGTC                       8  S000299\t"; grep -P "TACGTGTC|GACACGTA" $1 | wc -l
echo -ne "unknown         ABREMOTIFIIIOSRAB16B GCCGCGTGGC                     10 S000291\t"; grep -P "GCCGCGTGGC|GCCACGCGGC" $1 | wc -l
echo -ne "unknown         ABREMOTIFIOSRAB16B   AGTACGTGGC                     10 S000290\t"; grep -P "AGTACGTGGC|GCCACGTACT" $1 | wc -l
echo -ne "unknown         ABREOSRAB21          ACGTSSSC                       8  S000012\t"; grep -P "ACGT[GC]SSC|GSS[GC]ACGT" $1 | wc -l
echo -ne "unknown         ABRERATCAL           MACGYGB                        7  S000507\t"; grep -P "[AC]ACG[CT]G[GTC]|[GAC]C[AG]CGT[GT]" $1 | wc -l
echo -ne "unknown         ABRETAEM             GGACACGTGGC                    11 S000015\t"; grep -P "GGACACGTGGC|GCCACGTGTCC" $1 | wc -l
echo -ne "unknown         ABREZMRAB28          CCACGTGG                       8  S000133\t"; grep -P "CCACGTGG|CCACGTGG" $1 | wc -l
echo -ne "unknown         ACEATCHS             GACACGTAGA                     10 S000355\t"; grep -P "GACACGTAGA|TCTACGTGTC" $1 | wc -l
echo -ne "unknown         ACGTABOX             TACGTA                         6  S000130\t"; grep -P "TACGTA|TACGTA" $1 | wc -l
echo -ne "unknown         ACGTABREMOTIFA2OSEM  ACGTGKC                        7  S000394\t"; grep -P "ACGTG[GT]C|G[AC]CACGT" $1 | wc -l
echo -ne "unknown         ACGTABREMOTIFAOSOSEM TACGTGTC                       8  S000281\t"; grep -P "TACGTGTC|GACACGTA" $1 | wc -l
echo -ne "unknown         ACGTATERD1           ACGT                           4  S000415\t"; grep -P "ACGT|ACGT" $1 | wc -l
echo -ne "unknown         ACGTCBOX             GACGTC                         6  S000131\t"; grep -P "GACGTC|GACGTC" $1 | wc -l
echo -ne "unknown         ACGTOSGLUB1          GTACGTG                        7  S000278\t"; grep -P "GTACGTG|CACGTAC" $1 | wc -l
echo -ne "unknown         ACGTROOT1            GCCACGTGGC                     10 S000016\t"; grep -P "GCCACGTGGC|GCCACGTGGC" $1 | wc -l
echo -ne "unknown         ACGTSEED2            ACACACGTCAA                    11 S000018\t"; grep -P "ACACACGTCAA|TTGACGTGTGT" $1 | wc -l
echo -ne "unknown         ACGTSEED3            GTACGTGGCG                     10 S000019\t"; grep -P "GTACGTGGCG|CGCCACGTAC" $1 | wc -l
echo -ne "unknown         ACGTTBOX             AACGTT                         6  S000132\t"; grep -P "AACGTT|AACGTT" $1 | wc -l
echo -ne "unknown         ACIIIPVPAL2          GTTAGGTTC                      9  S000194\t"; grep -P "GTTAGGTTC|GAACCTAAC" $1 | wc -l
echo -ne "unknown         ACIIPVPAL2           CCACCAACCCCC                   12 S000193\t"; grep -P "CCACCAACCCCC|GGGGGTTGGTGG" $1 | wc -l
echo -ne "unknown         ACIPVPAL2            CCCACCTACC                     10 S000192\t"; grep -P "CCCACCTACC|GGTAGGTGGG" $1 | wc -l
echo -ne "unknown         AGAMOUSATCONSENSUS   TTDCCWWWWWWGGHAA               16 S000342\t"; grep -P "TT[GAT]CC[AT]WWWWWGG[ATC]AA|TT[GAT]CCWWWWW[AT]GG[ATC]AA" $1 | wc -l
echo -ne "unknown         AGATCONSENSUS        TTWCCWWWWNNGGWW                15 S000316\t"; grep -P "TT[AT]CCWWWW[ATCG]NGGWW|WWCCN[CGAT]WWWWGG[AT]AA" $1 | wc -l
echo -ne "unknown         AGCBOXNPGLB          AGCCGCC                        7  S000232\t"; grep -P "AGCCGCC|GGCGGCT" $1 | wc -l
echo -ne "unknown         AGL1ATCONSENSUS      NTTDCCWWWWNNGGWAAN             18 S000338\t"; grep -P "[ATCG]TT[GAT]CC[AT]WWWNNGGWAAN|NTTWCCNNWWW[AT]GG[ATC]AA[CGAT]" $1 | wc -l
echo -ne "unknown         AGL2ATCONSENSUS      NNWNCCAWWWWTRGWWAN             18 S000339\t"; grep -P "[ATCG]N[AT]NCCAWWWWT[AG]GWWAN|NTWWC[CT]AWWWWTGGN[AT]N[CGAT]" $1 | wc -l
echo -ne "unknown         AGL3ATCONSENSUS      TTWCYAWWWWTRGWAA               16 S000343\t"; grep -P "TT[AT]C[CT]AWWWWT[AG]GWAA|TTWC[CT]AWWWWT[AG]G[AT]AA" $1 | wc -l
echo -ne "unknown         AGMOTIFNTMYB2        AGATCCAA                       8  S000444\t"; grep -P "AGATCCAA|TTGGATCT" $1 | wc -l
echo -ne "unknown         AGTACSAO             AAAAAGTAAAAAGTAAAAAAGTAAAAAG   28 S000258\t"; grep -P "AAAAAGTAAAAAGTAAAAAAGTAAAAAG|CTTTTTACTTTTTTACTTTTTACTTTTT" $1 | wc -l
echo -ne "unknown         ALF1NTPARC           TTACGCAAGCAATGACA              17 S000238\t"; grep -P "TTACGCAAGCAATGACA|TGTCATTGCTTGCGTAA" $1 | wc -l
echo -ne "unknown         ALF2NTPARB           TGAGGAGACTTGTGAGGT             18 S000239\t"; grep -P "TGAGGAGACTTGTGAGGT|ACCTCACAAGTCTCCTCA" $1 | wc -l
echo -ne "unknown         AMMORESIIUDCRNIA1    GGWAGGGT                       8  S000374\t"; grep -P "GG[AT]AGGGT|ACCCT[AT]CC" $1 | wc -l
echo -ne "unknown         AMMORESIVDCRNIA1     CGAACTT                        7  S000375\t"; grep -P "CGAACTT|AAGTTCG" $1 | wc -l
echo -ne "unknown         AMMORESVDCRNIA1      GGCCCCGGG                      9  S000376\t"; grep -P "GGCCCCGGG|CCCGGGGCC" $1 | wc -l
echo -ne "unknown         AMYBOX1              TAACARA                        7  S000020\t"; grep -P "TAACA[AG]A|T[CT]TGTTA" $1 | wc -l
echo -ne "unknown         AMYBOX2              TATCCAT                        7  S000021\t"; grep -P "TATCCAT|ATGGATA" $1 | wc -l
echo -ne "unknown         ANAERO1CONSENSUS     AAACAAA                        7  S000477\t"; grep -P "AAACAAA|TTTGTTT" $1 | wc -l
echo -ne "unknown         ANAERO2CONSENSUS     AGCAGC                         6  S000478\t"; grep -P "AGCAGC|GCTGCT" $1 | wc -l
echo -ne "unknown         ANAERO3CONSENSUS     TCATCAC                        7  S000479\t"; grep -P "TCATCAC|GTGATGA" $1 | wc -l
echo -ne "unknown         ANAERO4CONSENSUS     GTTTHGCAA                      9  S000480\t"; grep -P "GTTT[ATC]GCAA|TTGC[GAT]AAAC" $1 | wc -l
echo -ne "unknown         ANAERO5CONSENSUS     TTCCCTGTT                      9  S000481\t"; grep -P "TTCCCTGTT|AACAGGGAA" $1 | wc -l
echo -ne "unknown         ANAEROBICCISZMGAPC4  CGAAACCAGCAACGGTCCAG           20 S000350\t"; grep -P "CGAAACCAGCAACGGTCCAG|CTGGACCGTTGCTGGTTTCG" $1 | wc -l
echo -ne "unknown         ARE1                 RGTGACNNNGC                    11 S000022\t"; grep -P "[AG]GTGAC[ATCG]NNGC|GCNN[CGAT]GTCAC[CT]" $1 | wc -l
echo -ne "unknown         ARECOREZMGAPC4       AGCAACGGTC                     10 S000393\t"; grep -P "AGCAACGGTC|GACCGTTGCT" $1 | wc -l
echo -ne "unknown         ARELIKEGHPGDFR2      AGTTGAATGGGGGTGCA              17 S000437\t"; grep -P "AGTTGAATGGGGGTGCA|TGCACCCCCATTCAACT" $1 | wc -l
echo -ne "unknown         ARFAT                TGTCTC                         6  S000270\t"; grep -P "TGTCTC|GAGACA" $1 | wc -l
echo -ne "unknown         ARR1AT               NGATT                          5  S000454\t"; grep -P "[ATCG]GATT|AATC[CGAT]" $1 | wc -l
echo -ne "unknown         AS1CAMV              CCACTGACGTAAGGGATGACGCACAATCC  29 S000023\t"; grep -P "CCACTGACGTAAGGGATGACGCACAATCC|GGATTGTGCGTCATCCCTTACGTCAGTGG" $1 | wc -l
echo -ne "unknown         AS1LIKECSHPRA        AAATGACGAAAATGC                15 S000260\t"; grep -P "AAATGACGAAAATGC|GCATTTTCGTCATTT" $1 | wc -l
echo -ne "unknown         ASF1ATNOS            TGAGCTAAGCACATACGTCAG          21 S000073\t"; grep -P "TGAGCTAAGCACATACGTCAG|CTGACGTATGTGCTTAGCTCA" $1 | wc -l
echo -ne "unknown         ASF1MOTIFCAMV        TGACG                          5  S000024\t"; grep -P "TGACG|CGTCA" $1 | wc -l
echo -ne "unknown         ASF1NTPARA           TTACGCAAGCAATGACAT             18 S000240\t"; grep -P "TTACGCAAGCAATGACAT|ATGTCATTGCTTGCGTAA" $1 | wc -l
echo -ne "unknown         AT1BOX               AATATTTTTATT                   12 S000025\t"; grep -P "AATATTTTTATT|AATAAAAATATT" $1 | wc -l
echo -ne "unknown         ATHB1ATCONSENSUS     CAATWATTG                      9  S000317\t"; grep -P "CAAT[AT]ATTG|CAAT[AT]ATTG" $1 | wc -l
echo -ne "unknown         ATHB2ATCONSENSUS     CAATSATTG                      9  S000318\t"; grep -P "CAAT[GC]ATTG|CAAT[GC]ATTG" $1 | wc -l
echo -ne "unknown         ATHB5ATCORE          CAATNATTG                      9  S000371\t"; grep -P "CAAT[ATCG]ATTG|CAAT[CGAT]ATTG" $1 | wc -l
echo -ne "unknown         ATHB6COREAT          CAATTATTA                      9  S000399\t"; grep -P "CAATTATTA|TAATAATTG" $1 | wc -l
echo -ne "unknown         ATRICHPSPETE         AATATACTAGTATTATTTACTAAAAAAAATC 31 S000248\t"; grep -P "AATATACTAGTATTATTTACTAAAAAAAATC|GATTTTTTTTAGTAAATAATACTAGTATATT" $1 | wc -l
echo -ne "unknown         AUXREPSIAA4          KGTCCCAT                       8  S000026\t"; grep -P "[GT]GTCCCAT|ATGGGAC[AC]" $1 | wc -l
echo -ne "unknown         AUXRETGA1GMGH3       TGACGTAA                       8  S000234\t"; grep -P "TGACGTAA|TTACGTCA" $1 | wc -l
echo -ne "unknown         AUXRETGA2GMGH3       TGACGTGGC                      9  S000235\t"; grep -P "TGACGTGGC|GCCACGTCA" $1 | wc -l
echo -ne "unknown         B2GMAUX28            CTTGTCGTCA                     10 S000325\t"; grep -P "CTTGTCGTCA|TGACGACAAG" $1 | wc -l
echo -ne "unknown         BBOXSITE1STPAT       GCTAAACAAT                     10 S000398\t"; grep -P "GCTAAACAAT|ATTGTTTAGC" $1 | wc -l
echo -ne "unknown         BIHD1OS              TGTCA                          5  S000498\t"; grep -P "TGTCA|TGACA" $1 | wc -l
echo -ne "unknown         BOX1PSGS2            ATAGAAATCAA                    11 S000222\t"; grep -P "ATAGAAATCAA|TTGATTTCTAT" $1 | wc -l
echo -ne "unknown         BOX1PVCHS15          TAAAAGTTAAAAAC                 14 S000208\t"; grep -P "TAAAAGTTAAAAAC|GTTTTTAACTTTTA" $1 | wc -l
echo -ne "unknown         BOX2PSGS2            TCTAAGCAAAG                    11 S000204\t"; grep -P "TCTAAGCAAAG|CTTTGCTTAGA" $1 | wc -l
echo -ne "unknown         BOX2PVCHS15          CTGTGATTAAATAT                 14 S000209\t"; grep -P "CTGTGATTAAATAT|ATATTTAATCACAG" $1 | wc -l
echo -ne "unknown         BOX3PVCHS15          TATTGGTTACTAAA                 14 S000210\t"; grep -P "TATTGGTTACTAAA|TTTAGTAACCAATA" $1 | wc -l
echo -ne "unknown         BOXBPSAS1            AAACGACACCGTTT                 14 S000225\t"; grep -P "AAACGACACCGTTT|AAACGGTGTCGTTT" $1 | wc -l
echo -ne "unknown         BOXC'PSAS1           TCCCGGTACACACTTCTT             18 S000227\t"; grep -P "TCCCGGTACACACTTCTT|AAGAAGTGTGTACCGGGA" $1 | wc -l
echo -ne "unknown         BOXCPSAS1            CTCCCAC                        7  S000226\t"; grep -P "CTCCCAC|GTGGGAG" $1 | wc -l
echo -ne "unknown         BOXICHS              GTCCMTCMAACCTAMC               16 S000228\t"; grep -P "GTCC[AC]TCMAACCTAMC|GMTAGGTTMGA[GT]GGAC" $1 | wc -l
echo -ne "unknown         BOXIINTPATPB         ATAGAA                         6  S000296\t"; grep -P "ATAGAA|TTCTAT" $1 | wc -l
echo -ne "unknown         BOXIIPCCHS           ACGTGGC                        7  S000229\t"; grep -P "ACGTGGC|GCCACGT" $1 | wc -l
echo -ne "unknown         BOXINTPATPB          AATTCCATAGAATAGATAATA          21 S000295\t"; grep -P "AATTCCATAGAATAGATAATA|TATTATCTATTCTATGGAATT" $1 | wc -l
echo -ne "unknown         BOXLCOREDCPAL        ACCWWCC                        7  S000492\t"; grep -P "ACC[AT]WCC|GGW[AT]GGT" $1 | wc -l
echo -ne "unknown         BP5OSWX              CAACGTG                        7  S000436\t"; grep -P "CAACGTG|CACGTTG" $1 | wc -l
echo -ne "unknown         BS1EGCCR             AGCGGG                         6  S000352\t"; grep -P "AGCGGG|CCCGCT" $1 | wc -l
echo -ne "unknown         C1GMAUX28            TGAAAACAGTGAGTTA               16 S000326\t"; grep -P "TGAAAACAGTGAGTTA|TAACTCACTGTTTTCA" $1 | wc -l
echo -ne "unknown         C1MOTIFZMBZ2         TAACTSAGTTA                    11 S000237\t"; grep -P "TAACT[GC]AGTTA|TAACT[GC]AGTTA" $1 | wc -l
echo -ne "unknown         C2GMAUX28            AATAATAATAATAATAAATA           20 S000327\t"; grep -P "AATAATAATAATAATAAATA|TATTTATTATTATTATTATT" $1 | wc -l
echo -ne "unknown         CAATBOX1             CAAT                           4  S000028\t"; grep -P "CAAT|ATTG" $1 | wc -l
echo -ne "unknown         CAATBOX2             GGCCAATCT                      9  S000029\t"; grep -P "GGCCAATCT|AGATTGGCC" $1 | wc -l
echo -ne "unknown         CACGCAATGMGH3        CACGCAAT                       8  S000368\t"; grep -P "CACGCAAT|ATTGCGTG" $1 | wc -l
echo -ne "unknown         CACGTGMOTIF          CACGTG                         6  S000042\t"; grep -P "CACGTG|CACGTG" $1 | wc -l
echo -ne "unknown         CACTFTPPCA1          YACT                           4  S000449\t"; grep -P "[CT]ACT|AGT[AG]" $1 | wc -l
echo -ne "unknown         CANBNNAPA            CNAACAC                        7  S000148\t"; grep -P "C[ATCG]AACAC|GTGTT[CGAT]G" $1 | wc -l
echo -ne "unknown         CAREOSREP1           CAACTC                         6  S000421\t"; grep -P "CAACTC|GAGTTG" $1 | wc -l
echo -ne "unknown         CARG1ATAP3           GTTTACATAAATGGAAAA             18 S000347\t"; grep -P "GTTTACATAAATGGAAAA|TTTTCCATTTATGTAAAC" $1 | wc -l
echo -ne "unknown         CARG2ATAP3           CTTACCTTTCATGGATTA             18 S000348\t"; grep -P "CTTACCTTTCATGGATTA|TAATCCATGAAAGGTAAG" $1 | wc -l
echo -ne "unknown         CARG3ATAP3           CTTTCCATTTTTAGTAAC             18 S000349\t"; grep -P "CTTTCCATTTTTAGTAAC|GTTACTAAAAATGGAAAG" $1 | wc -l
echo -ne "unknown         CARGATCONSENSUS      CCWWWWWWGG                     10 S000404\t"; grep -P "CC[AT]WWWWWGG|CCWWWWW[AT]GG" $1 | wc -l
echo -ne "unknown         CARGCW8GAT           CWWWWWWWWG                     10 S000431\t"; grep -P "C[AT]WWWWWWWG|CWWWWWWW[AT]G" $1 | wc -l
echo -ne "unknown         CARGNCAT             CCWWWWWWWWGG                   12 S000446\t"; grep -P "CC[AT]WWWWWWWGG|CCWWWWWWW[AT]GG" $1 | wc -l
echo -ne "unknown         CATATGGMSAUR         CATATG                         6  S000370\t"; grep -P "CATATG|CATATG" $1 | wc -l
echo -ne "unknown         CBFHV                RYCGAC                         6  S000497\t"; grep -P "[AG][CT]CGAC|GTCG[AG][CT]" $1 | wc -l
echo -ne "unknown         CCA1ATLHCB1          AAMAATCT                       8  S000149\t"; grep -P "AA[AC]AATCT|AGATT[GT]TT" $1 | wc -l
echo -ne "unknown         CCAATBOX1            CCAAT                          5  S000030\t"; grep -P "CCAAT|ATTGG" $1 | wc -l
echo -ne "unknown         CCTCGTGTCTCGMGH3     CCTCGTGTCTC                    11 S000369\t"; grep -P "CCTCGTGTCTC|GAGACACGAGG" $1 | wc -l
echo -ne "unknown         CDA1ATCAB2           CAAAACGC                       8  S000440\t"; grep -P "CAAAACGC|GCGTTTTG" $1 | wc -l
echo -ne "unknown         CE3OSOSEM            AACGCGTGTC                     10 S000282\t"; grep -P "AACGCGTGTC|GACACGCGTT" $1 | wc -l
echo -ne "unknown         CELLCYCLESC          CACGAAAA                       8  S000031\t"; grep -P "CACGAAAA|TTTTCGTG" $1 | wc -l
echo -ne "unknown         CEREGLUBOX1PSLEGA    TGTTAAAGT                      9  S000032\t"; grep -P "TGTTAAAGT|ACTTTAACA" $1 | wc -l
echo -ne "unknown         CEREGLUBOX2PSLEGA    TGAAAACT                       8  S000033\t"; grep -P "TGAAAACT|AGTTTTCA" $1 | wc -l
echo -ne "unknown         CEREGLUBOX3PSLEGA    TGTAAAAGT                      9  S000034\t"; grep -P "TGTAAAAGT|ACTTTTACA" $1 | wc -l
echo -ne "unknown         CGACGOSAMY3          CGACG                          5  S000205\t"; grep -P "CGACG|CGTCG" $1 | wc -l
echo -ne "unknown         CGCGBOXAT            VCGCGB                         6  S000501\t"; grep -P "[GAC]CGCG[GTC]|[GAC]CGCG[GTC]" $1 | wc -l
echo -ne "unknown         CGF1ATCAB2           GATAAAGATTACTTCAGATATAACAAACGTTAC 33 S000213\t"; grep -P "GATAAAGATTACTTCAGATATAACAAACGTTAC|GTAACGTTTGTTATATCTGAAGTAATCTTTATC" $1 | wc -l
echo -ne "unknown         CGTGTSPHZMC1         CGTGTCGTCCATGCAT               16 S000294\t"; grep -P "CGTGTCGTCCATGCAT|ATGCATGGACGACACG" $1 | wc -l
echo -ne "unknown         CIACADIANLELHC       CAANNNNATC                     10 S000252\t"; grep -P "CAA[ATCG]NNNATC|GATNNN[CGAT]TTG" $1 | wc -l
echo -ne "unknown         CMSRE1IBSPOA         TGGACGG                        7  S000511\t"; grep -P "TGGACGG|CCGTCCA" $1 | wc -l
echo -ne "unknown         CONSERVED11NTZMATP1  ACGTATTAAAA                    11 S000301\t"; grep -P "ACGTATTAAAA|TTTTAATACGT" $1 | wc -l
echo -ne "unknown         COREOS               AAKAATWYRTAWATAAAAMTTTTATWTA   28 S000469\t"; grep -P "AA[GT]AAT[AT][CT][AG]TAWATAAAA[AC]TTTTATWTA|TAWATAAAA[GT]TTTTATWTA[CT][AG][AT]ATT[AC]TT" $1 | wc -l
echo -ne "unknown         CPBCSPOR             TATTAG                         6  S000491\t"; grep -P "TATTAG|CTAATA" $1 | wc -l
echo -ne "unknown         CPRFPCCHS            CCACGTGGCC                     10 S000313\t"; grep -P "CCACGTGGCC|GGCCACGTGG" $1 | wc -l
echo -ne "unknown         CRTDREHVCBF2         GTCGAC                         6  S000411\t"; grep -P "GTCGAC|GTCGAC" $1 | wc -l
echo -ne "unknown         CTRMCAMV35S          TCTCTCTCT                      9  S000460\t"; grep -P "TCTCTCTCT|AGAGAGAGA" $1 | wc -l
echo -ne "unknown         CURECORECR           GTAC                           4  S000493\t"; grep -P "GTAC|GTAC" $1 | wc -l
echo -ne "unknown         CYTOSITECSHPRA       AAGATTGATTGAG                  13 S000261\t"; grep -P "AAGATTGATTGAG|CTCAATCAATCTT" $1 | wc -l
echo -ne "unknown         D1GMAUX28            ACAGTTACTA                     10 S000328\t"; grep -P "ACAGTTACTA|TAGTAACTGT" $1 | wc -l
echo -ne "unknown         D2GMAUX28            ATTTATATAAAT                   12 S000329\t"; grep -P "ATTTATATAAAT|ATTTATATAAAT" $1 | wc -l
echo -ne "unknown         D3GMAUX28            TATTTGCTTAA                    11 S000330\t"; grep -P "TATTTGCTTAA|TTAAGCAAATA" $1 | wc -l
echo -ne "unknown         D4GMAUX28            TAGTGCTGT                      9  S000331\t"; grep -P "TAGTGCTGT|ACAGCACTA" $1 | wc -l
echo -ne "unknown         DE1PSPRA2            GGATTTTACAGT                   12 S000379\t"; grep -P "GGATTTTACAGT|ACTGTAAAATCC" $1 | wc -l
echo -ne "unknown         DOFCOREZM            AAAG                           4  S000265\t"; grep -P "AAAG|CTTT" $1 | wc -l
echo -ne "unknown         DPBFCOREDCDC3        ACACNNG                        7  S000292\t"; grep -P "ACAC[ATCG]NG|CN[CGAT]GTGT" $1 | wc -l
echo -ne "unknown         DR5GMGH3             CCTTTTGTCTC                    11 S000337\t"; grep -P "CCTTTTGTCTC|GAGACAAAAGG" $1 | wc -l
echo -ne "unknown         DRE1COREZMRAB17      ACCGAGA                        7  S000401\t"; grep -P "ACCGAGA|TCTCGGT" $1 | wc -l
echo -ne "unknown         DRE2COREZMRAB17      ACCGAC                         6  S000402\t"; grep -P "ACCGAC|GTCGGT" $1 | wc -l
echo -ne "unknown         DRECRTCOREAT         RCCGAC                         6  S000418\t"; grep -P "[AG]CCGAC|GTCGG[CT]" $1 | wc -l
echo -ne "unknown         DREDR1ATRD29AB       TACCGACAT                      9  S000152\t"; grep -P "TACCGACAT|ATGTCGGTA" $1 | wc -l
echo -ne "unknown         E2F1OSPCNA           GCGGGAAA                       8  S000396\t"; grep -P "GCGGGAAA|TTTCCCGC" $1 | wc -l
echo -ne "unknown         E2FANTRNR            TTTCCCGC                       8  S000366\t"; grep -P "TTTCCCGC|GCGGGAAA" $1 | wc -l
echo -ne "unknown         E2FAT                TYTCCCGCC                      9  S000417\t"; grep -P "T[CT]TCCCGCC|GGCGGGA[AG]A" $1 | wc -l
echo -ne "unknown         E2FBNTRNR            GCGGCAAA                       8  S000367\t"; grep -P "GCGGCAAA|TTTGCCGC" $1 | wc -l
echo -ne "unknown         E2FCONSENSUS         WTTSSCSS                       8  S000476\t"; grep -P "[AT]TT[GC]SCSS|SSGS[GC]AA[AT]" $1 | wc -l
echo -ne "unknown         EBOXBNNAPA           CANNTG                         6  S000144\t"; grep -P "CA[ATCG]NTG|CAN[CGAT]TG" $1 | wc -l
echo -ne "unknown         EECCRCAH1            GANTTNC                        7  S000494\t"; grep -P "GA[ATCG]TTNC|GNAA[CGAT]TC" $1 | wc -l
echo -ne "unknown         EIN3ATERF1           GGATTCAAGGGGCATGTATCTTGAATCC   28 S000332\t"; grep -P "GGATTCAAGGGGCATGTATCTTGAATCC|GGATTCAAGATACATGCCCCTTGAATCC" $1 | wc -l
echo -ne "unknown         ELEMENT1GMLBC3       GATATATTAATATTTTATTTTATA       24 S000319\t"; grep -P "GATATATTAATATTTTATTTTATA|TATAAAATAAAATATTAATATATC" $1 | wc -l
echo -ne "unknown         ELEMENT2GMLBC3       CTTAAATTATTTATTT               16 S000320\t"; grep -P "CTTAAATTATTTATTT|AAATAAATAATTTAAG" $1 | wc -l
echo -ne "unknown         ELRE1PCPAL1          CTCCAACAAACCCCTTC              17 S000306\t"; grep -P "CTCCAACAAACCCCTTC|GAAGGGGTTTGTTGGAG" $1 | wc -l
echo -ne "unknown         ELRE2PCPAL1          ATTCTCACCTACCA                 14 S000307\t"; grep -P "ATTCTCACCTACCA|TGGTAGGTGAGAAT" $1 | wc -l
echo -ne "unknown         ELRECOREPCRP1        TTGACC                         6  S000142\t"; grep -P "TTGACC|GGTCAA" $1 | wc -l
echo -ne "unknown         ELRENTCHN50          GGTCANNNAGTC                   12 S000155\t"; grep -P "GGTCA[ATCG]NNAGTC|GACTNN[CGAT]TGACC" $1 | wc -l
echo -ne "unknown         EMBP1TAEM            CACGTGGC                       8  S000119\t"; grep -P "CACGTGGC|GCCACGTG" $1 | wc -l
echo -ne "unknown         EMHVCHORD            TGTAAAGT                       8  S000452\t"; grep -P "TGTAAAGT|ACTTTACA" $1 | wc -l
echo -ne "unknown         EREGCC               TAAGAGCCGCC                    11 S000036\t"; grep -P "TAAGAGCCGCC|GGCGGCTCTTA" $1 | wc -l
echo -ne "unknown         ERELEE4              AWTTCAAA                       8  S000037\t"; grep -P "A[AT]TTCAAA|TTTGAA[AT]T" $1 | wc -l
echo -ne "unknown         ESPASGL01            ACATGTCATCATGT                 14 S000509\t"; grep -P "ACATGTCATCATGT|ACATGATGACATGT" $1 | wc -l
echo -ne "unknown         EVENINGAT            AAAATATCT                      9  S000385\t"; grep -P "AAAATATCT|AGATATTTT" $1 | wc -l
echo -ne "unknown         GADOWNAT             ACGTGTC                        7  S000438\t"; grep -P "ACGTGTC|GACACGT" $1 | wc -l
echo -ne "unknown         GAGA8HVBKN3          GAGAGAGAGAGAGAGA               16 S000427\t"; grep -P "GAGAGAGAGAGAGAGA|TCTCTCTCTCTCTCTC" $1 | wc -l
echo -ne "unknown         GAGAGMGSA1           GAGAGAGAGAGAGAGAGA             18 S000405\t"; grep -P "GAGAGAGAGAGAGAGAGA|TCTCTCTCTCTCTCTCTC" $1 | wc -l
echo -ne "unknown         GARE1OSREP1          TAACAGA                        7  S000419\t"; grep -P "TAACAGA|TCTGTTA" $1 | wc -l
echo -ne "unknown         GARE2                RTAACARANTCYGG                 14 S000165\t"; grep -P "[AG]TAACARA[ATCG]TC[CT]GG|CC[AG]GA[CGAT]TRTGTTA[CT]" $1 | wc -l
echo -ne "unknown         GARE2OSREP1          TAACGTA                        7  S000420\t"; grep -P "TAACGTA|TACGTTA" $1 | wc -l
echo -ne "unknown         GARE4HVEPB1          GTAACAGAATGCTGG                15 S000297\t"; grep -P "GTAACAGAATGCTGG|CCAGCATTCTGTTAC" $1 | wc -l
echo -ne "unknown         GAREAT               TAACAAR                        7  S000439\t"; grep -P "TAACAA[AG]|[CT]TTGTTA" $1 | wc -l
echo -ne "unknown         GAREHVAMY1           GGCCGATAACAAACTCCGGCC          21 S000038\t"; grep -P "GGCCGATAACAAACTCCGGCC|GGCCGGAGTTTGTTATCGGCC" $1 | wc -l
echo -ne "unknown         GATABOX              GATA                           4  S000039\t"; grep -P "GATA|TATC" $1 | wc -l
echo -ne "unknown         GBOX10NT             GCCACGTGCC                     10 S000272\t"; grep -P "GCCACGTGCC|GGCACGTGGC" $1 | wc -l
echo -ne "unknown         GBOXLERBCS           MCACGTGGC                      9  S000041\t"; grep -P "[AC]CACGTGGC|GCCACGTG[GT]" $1 | wc -l
echo -ne "unknown         GBOXPC               ACCACGTGGC                     10 S000324\t"; grep -P "ACCACGTGGC|GCCACGTGGT" $1 | wc -l
echo -ne "unknown         GBOXRELOSAMY3        CTACGTGGCCA                    11 S000206\t"; grep -P "CTACGTGGCCA|TGGCCACGTAG" $1 | wc -l
echo -ne "unknown         GBOXSORBCS1          TCCACGTGGT                     10 S000380\t"; grep -P "TCCACGTGGT|ACCACGTGGA" $1 | wc -l
echo -ne "unknown         GCAACREPEATZMZEIN    GCAACGCAAC                     10 S000027\t"; grep -P "GCAACGCAAC|GTTGCGTTGC" $1 | wc -l
echo -ne "unknown         GCBP2ZMGAPC4         GTGGGCCCG                      9  S000351\t"; grep -P "GTGGGCCCG|CGGGCCCAC" $1 | wc -l
echo -ne "unknown         GCCCORE              GCCGCC                         6  S000430\t"; grep -P "GCCGCC|GGCGGC" $1 | wc -l
echo -ne "unknown         GCN4OSGLUB1          TGAGTCA                        7  S000277\t"; grep -P "TGAGTCA|TGACTCA" $1 | wc -l
echo -ne "unknown         GGTCCCATGMSAUR       GGTCCCAT                       8  S000360\t"; grep -P "GGTCCCAT|ATGGGACC" $1 | wc -l
echo -ne "unknown         GLMHVCHORD           RTGASTCAT                      9  S000451\t"; grep -P "[AG]TGA[GC]TCAT|ATGA[GC]TCA[CT]" $1 | wc -l
echo -ne "unknown         GLUTAACAOS           AACAAACTCTAT                   12 S000045\t"; grep -P "AACAAACTCTAT|ATAGAGTTTGTT" $1 | wc -l
echo -ne "unknown         GLUTEBOX1OSGT2       ATATCATGAGTCACTTCA             18 S000046\t"; grep -P "ATATCATGAGTCACTTCA|TGAAGTGACTCATGATAT" $1 | wc -l
echo -ne "unknown         GLUTEBOX1OSGT3       TATCTAGTGAGTCACTTCA            19 S000128\t"; grep -P "TATCTAGTGAGTCACTTCA|TGAAGTGACTCACTAGATA" $1 | wc -l
echo -ne "unknown         GLUTEBOX2OSGT2       TCCGTGTACCA                    11 S000047\t"; grep -P "TCCGTGTACCA|TGGTACACGGA" $1 | wc -l
echo -ne "unknown         GLUTEBOX2OSGT3       CTTTTGTGTACCTTA                15 S000129\t"; grep -P "CTTTTGTGTACCTTA|TAAGGTACACAAAAG" $1 | wc -l
echo -ne "unknown         GLUTEBP1OS           AAGCAACACACAAC                 14 S000048\t"; grep -P "AAGCAACACACAAC|GTTGTGTGTTGCTT" $1 | wc -l
echo -ne "unknown         GLUTEBP2OS           ATGCTCAATAGATATAAGT            19 S000049\t"; grep -P "ATGCTCAATAGATATAAGT|ACTTATATCTATTGAGCAT" $1 | wc -l
echo -ne "unknown         GLUTECOREOS          CTTTCGTGTAC                    11 S000050\t"; grep -P "CTTTCGTGTAC|GTACACGAAAG" $1 | wc -l
echo -ne "unknown         GMHDLGMVSPB          CATTAATTAG                     10 S000372\t"; grep -P "CATTAATTAG|CTAATTAATG" $1 | wc -l
echo -ne "unknown         GRAZMRAB17           CACTGGCCGCCC                   12 S000150\t"; grep -P "CACTGGCCGCCC|GGGCGGCCAGTG" $1 | wc -l
echo -ne "unknown         GRAZMRAB28           CATGCCGCC                      9  S000220\t"; grep -P "CATGCCGCC|GGCGGCATG" $1 | wc -l
echo -ne "unknown         GREGIONNTPRB1B       TGGCGGCTCTTATCTCACGTGATG       24 S000364\t"; grep -P "TGGCGGCTCTTATCTCACGTGATG|CATCACGTGAGATAAGAGCCGCCA" $1 | wc -l
echo -ne "unknown         GT1CONSENSUS         GRWAAW                         6  S000198\t"; grep -P "G[AG][AT]AAW|WTT[AT][CT]C" $1 | wc -l
echo -ne "unknown         GT1CORE              GGTTAA                         6  S000125\t"; grep -P "GGTTAA|TTAACC" $1 | wc -l
echo -ne "unknown         GT1GMSCAM4           GAAAAA                         6  S000453\t"; grep -P "GAAAAA|TTTTTC" $1 | wc -l
echo -ne "unknown         GT1MOTIFPSRBCS       KWGTGRWAAWRW                   12 S000051\t"; grep -P "[GT][AT]GTG[AG]WAAWRW|WRWTTW[CT]CAC[AT][AC]" $1 | wc -l
echo -ne "unknown         GT2OSPHYA            GCGGTAATT                      9  S000207\t"; grep -P "GCGGTAATT|AATTACCGC" $1 | wc -l
echo -ne "unknown         GTGANTG10            GTGA                           4  S000378\t"; grep -P "GTGA|TCAC" $1 | wc -l
echo -ne "unknown         HBOXCONSENSUSPVCHS   CCTACCNNNNNNNCT                15 S000200\t"; grep -P "CCTACC[ATCG]NNNNNNCT|AGNNNNNN[CGAT]GGTAGG" $1 | wc -l
echo -ne "unknown         HBOXPVCHS15          CCTACCNNNNNNNCTNNNNA           20 S000361\t"; grep -P "CCTACC[ATCG]NNNNNNCTNNNNA|TNNNNAGNNNNNN[CGAT]GGTAGG" $1 | wc -l
echo -ne "unknown         HDMOTIFPCPR2         CTAATTGTTTA                    11 S000233\t"; grep -P "CTAATTGTTTA|TAAACAATTAG" $1 | wc -l
echo -ne "unknown         HDZIP2ATATHB2        TAATMATTA                      9  S000373\t"; grep -P "TAAT[AC]ATTA|TAAT[GT]ATTA" $1 | wc -l
echo -ne "unknown         HDZIPIIIAT           GTAATSATTAC                    11 S000475\t"; grep -P "GTAAT[GC]ATTAC|GTAAT[GC]ATTAC" $1 | wc -l
echo -ne "unknown         HEXAMERATH4          CCGTCG                         6  S000146\t"; grep -P "CCGTCG|CGACGG" $1 | wc -l
echo -ne "unknown         HEXAT                TGACGTGG                       8  S000334\t"; grep -P "TGACGTGG|CCACGTCA" $1 | wc -l
echo -ne "unknown         HEXMOTIFTAH3H4       ACGTCA                         6  S000053\t"; grep -P "ACGTCA|TGACGT" $1 | wc -l
echo -ne "unknown         HSE                  CTNGAANNTTCNAG                 14 S000054\t"; grep -P "CT[ATCG]GAANNTTCNAG|CTNGAANNTTC[CGAT]AG" $1 | wc -l
echo -ne "unknown         HSELIKENTACIDICPR1   CNNGAANNNTTCNNG                15 S000056\t"; grep -P "C[ATCG]NGAANNNTTCNNG|CNNGAANNNTTCN[CGAT]G" $1 | wc -l
echo -ne "unknown         HSELIKENTGLN2        AGGAATTCCT                     10 S000057\t"; grep -P "AGGAATTCCT|AGGAATTCCT" $1 | wc -l
echo -ne "unknown         HSRENTHSR203J        CAAAATTTTGTA                   12 S000466\t"; grep -P "CAAAATTTTGTA|TACAAAATTTTG" $1 | wc -l
echo -ne "unknown         HY5AT                TGACACGTGGCA                   12 S000345\t"; grep -P "TGACACGTGGCA|TGCCACGTGTCA" $1 | wc -l
echo -ne "unknown         IBOX                 GATAAG                         6  S000124\t"; grep -P "GATAAG|CTTATC" $1 | wc -l
echo -ne "unknown         IBOXCORE             GATAA                          5  S000199\t"; grep -P "GATAA|TTATC" $1 | wc -l
echo -ne "unknown         IBOXCORENT           GATAAGR                        7  S000424\t"; grep -P "GATAAG[AG]|[CT]CTTATC" $1 | wc -l
echo -ne "unknown         IBOXLSCMCUCUMISIN    AGATATGATAAAA                  13 S000423\t"; grep -P "AGATATGATAAAA|TTTTATCATATCT" $1 | wc -l
echo -ne "unknown         IDE1HVIDS2           ATCAAGCATGCTTCTTGC             18 S000463\t"; grep -P "ATCAAGCATGCTTCTTGC|GCAAGAAGCATGCTTGAT" $1 | wc -l
echo -ne "unknown         IDE2HVIDS2           TTGAACGGCAAGTTTCACGCTGTCACT    27 S000464\t"; grep -P "TTGAACGGCAAGTTTCACGCTGTCACT|AGTGACAGCGTGAAACTTGCCGTTCAA" $1 | wc -l
echo -ne "unknown         IDRSZMFER1           CACGAGSCCKCCAC                 14 S000445\t"; grep -P "CACGAG[GC]CC[GT]CCAC|GTGG[AC]GG[GC]CTCGTG" $1 | wc -l
echo -ne "unknown         INRNTPSADB           YTCANTYY                       8  S000395\t"; grep -P "[CT]TCA[ATCG]TYY|YYA[CGAT]TGA[AG]" $1 | wc -l
echo -ne "unknown         INTRONLOWER          TGCAGG                         6  S000086\t"; grep -P "TGCAGG|CCTGCA" $1 | wc -l
echo -ne "unknown         INTRONUPPER          MAGGTAAGT                      9  S000085\t"; grep -P "[AC]AGGTAAGT|ACTTACCT[GT]" $1 | wc -l
echo -ne "unknown         IRO2OS               CACGTGG                        7  S000505\t"; grep -P "CACGTGG|CCACGTG" $1 | wc -l
echo -ne "unknown         JASE1ATOPR1          CGTCAATGAA                     10 S000388\t"; grep -P "CGTCAATGAA|TTCATTGACG" $1 | wc -l
echo -ne "unknown         JASE2ATOPR1          CATACGTCGTCAA                  13 S000389\t"; grep -P "CATACGTCGTCAA|TTGACGACGTATG" $1 | wc -l
echo -ne "unknown         JERECRSTR            CTCTTAGACCGCCTTCTTTGAAAG       24 S000384\t"; grep -P "CTCTTAGACCGCCTTCTTTGAAAG|CTTTCAAAGAAGGCGGTCTAAGAG" $1 | wc -l
echo -ne "unknown         L1BOXATPDF1          TAAATGYA                       8  S000386\t"; grep -P "TAAATG[CT]A|T[AG]CATTTA" $1 | wc -l
echo -ne "unknown         L1DCPAL1             ATTCACCTACCC                   12 S000504\t"; grep -P "ATTCACCTACCC|GGGTAGGTGAAT" $1 | wc -l
echo -ne "unknown         L4DCPAL1             AATCTCCAACCA                   12 S000503\t"; grep -P "AATCTCCAACCA|TGGTTGGAGATT" $1 | wc -l
echo -ne "unknown         LBOXLERBCS           AAATTAACCAA                    11 S000126\t"; grep -P "AAATTAACCAA|TTGGTTAATTT" $1 | wc -l
echo -ne "unknown         LEAFYATAG            CCAATGT                        7  S000432\t"; grep -P "CCAATGT|ACATTGG" $1 | wc -l
echo -ne "unknown         LECPLEACS2           TAAAATAT                       8  S000465\t"; grep -P "TAAAATAT|ATATTTTA" $1 | wc -l
echo -ne "unknown         LEGUMINBOXLEGA5      TCCATAGCCATGCAWRCTGMAGAATGTC   28 S000060\t"; grep -P "TCCATAGCCATGCA[AT][AG]CTG[AC]AGAATGTC|GACATTCT[GT]CAG[CT][AT]TGCATGGCTATGGA" $1 | wc -l
echo -ne "unknown         LREBOX2PSRBCS3       TGTGTGGTTAATATG                15 S000061\t"; grep -P "TGTGTGGTTAATATG|CATATTAACCACACA" $1 | wc -l
echo -ne "unknown         LREBOX3PSRBCS3       ACTATTTTCACTATC                15 S000062\t"; grep -P "ACTATTTTCACTATC|GATAGTGAAAATAGT" $1 | wc -l
echo -ne "unknown         LREBOXIIPCCHS1       TCCACGTGGC                     10 S000303\t"; grep -P "TCCACGTGGC|GCCACGTGGA" $1 | wc -l
echo -ne "unknown         LREBOXIPCCHS1        AACCTAACCT                     10 S000302\t"; grep -P "AACCTAACCT|AGGTTAGGTT" $1 | wc -l
echo -ne "unknown         LRENPCABE            ACGTGGCA                       8  S000231\t"; grep -P "ACGTGGCA|TGCCACGT" $1 | wc -l
echo -ne "unknown         LS5ATPR1             TCTACGTCAC                     10 S000323\t"; grep -P "TCTACGTCAC|GTGACGTAGA" $1 | wc -l
echo -ne "unknown         LS7ATPR1             ACGTCATAGA                     10 S000322\t"; grep -P "ACGTCATAGA|TCTATGACGT" $1 | wc -l
echo -ne "unknown         LTRE1HVBLT49         CCGAAA                         6  S000250\t"; grep -P "CCGAAA|TTTCGG" $1 | wc -l
echo -ne "unknown         LTREATLTI78          ACCGACA                        7  S000157\t"; grep -P "ACCGACA|TGTCGGT" $1 | wc -l
echo -ne "unknown         LTRECOREATCOR15      CCGAC                          5  S000153\t"; grep -P "CCGAC|GTCGG" $1 | wc -l
echo -ne "unknown         MARABOX1             AATAAAYAAA                     10 S000063\t"; grep -P "AATAAA[CT]AAA|TTT[AG]TTTATT" $1 | wc -l
echo -ne "unknown         MARARS               WTTTATRTTTW                    11 S000064\t"; grep -P "[AT]TTTAT[AG]TTTW|WAAA[CT]ATAAA[AT]" $1 | wc -l
echo -ne "unknown         MARCEN3              TGTTTWTGNTTTCCGAAANNNNWWW      25 S000065\t"; grep -P "TGTTT[AT]TG[ATCG]TTTCCGAAANNNNWWW|WWWNNNNTTTCGGAAA[CGAT]CA[AT]AAACA" $1 | wc -l
echo -ne "unknown         MARTBOX              TTWTWTTWTT                     10 S000067\t"; grep -P "TT[AT]TWTTWTT|AAWAAWA[AT]AA" $1 | wc -l
echo -ne "unknown         MEJARELELOX          GATACANNAATNTGATG              17 S000151\t"; grep -P "GATACA[ATCG]NAATNTGATG|CATCANATTN[CGAT]TGTATC" $1 | wc -l
echo -ne "unknown         MNF1ZMPPC1           GTGCCCTT                       8  S000251\t"; grep -P "GTGCCCTT|AAGGGCAC" $1 | wc -l
echo -ne "unknown         MREATCHS             TCTAACCTACCA                   12 S000356\t"; grep -P "TCTAACCTACCA|TGGTAGGTTAGA" $1 | wc -l
echo -ne "unknown         MRNA3ENDTAH3         AATGGAAATG                     10 S000069\t"; grep -P "AATGGAAATG|CATTTCCATT" $1 | wc -l
echo -ne "unknown         MRNASTA1CRPSBD       CUCUUTGUTTUU                   12 S000274\t"; grep -P "CUCUUTGUTTUU|UUAAUCAUUGUG" $1 | wc -l
echo -ne "unknown         MRNASTA2CRPSBD       UGAGUUG                        7  S000275\t"; grep -P "UGAGUUG|CUUCTCU" $1 | wc -l
echo -ne "unknown         MSACRCYM             AGACCGTTG                      9  S000236\t"; grep -P "AGACCGTTG|CAACGGTCT" $1 | wc -l
echo -ne "unknown         MYB1AT               WAACCA                         6  S000408\t"; grep -P "[AT]AACCA|TGGTT[AT]" $1 | wc -l
echo -ne "unknown         MYB1LEPR             GTTAGTT                        7  S000443\t"; grep -P "GTTAGTT|AACTAAC" $1 | wc -l
echo -ne "unknown         MYB26PS              GTTAGGTT                       8  S000182\t"; grep -P "GTTAGGTT|AACCTAAC" $1 | wc -l
echo -ne "unknown         MYB2AT               TAACTG                         6  S000177\t"; grep -P "TAACTG|CAGTTA" $1 | wc -l
echo -ne "unknown         MYB2CONSENSUSAT      YAACKG                         6  S000409\t"; grep -P "[CT]AAC[GT]G|C[AC]GTT[AG]" $1 | wc -l
echo -ne "unknown         MYBATRD22            CTAACCA                        7  S000175\t"; grep -P "CTAACCA|TGGTTAG" $1 | wc -l
echo -ne "unknown         MYBCORE              CNGTTR                         6  S000176\t"; grep -P "C[ATCG]GTT[AG]|[CT]AAC[CGAT]G" $1 | wc -l
echo -ne "unknown         MYBCOREATCYCB1       AACGG                          5  S000502\t"; grep -P "AACGG|CCGTT" $1 | wc -l
echo -ne "unknown         MYBGAHV              TAACAAA                        7  S000181\t"; grep -P "TAACAAA|TTTGTTA" $1 | wc -l
echo -ne "unknown         MYBPLANT             MACCWAMC                       8  S000167\t"; grep -P "[AC]ACC[AT]AMC|GMT[AT]GGT[GT]" $1 | wc -l
echo -ne "unknown         MYBPZM               CCWACC                         6  S000179\t"; grep -P "CC[AT]ACC|GGT[AT]GG" $1 | wc -l
echo -ne "unknown         MYBST1               GGATA                          5  S000180\t"; grep -P "GGATA|TATCC" $1 | wc -l
echo -ne "unknown         MYCATERD1            CATGTG                         6  S000413\t"; grep -P "CATGTG|CACATG" $1 | wc -l
echo -ne "unknown         MYCATRD22            CACATG                         6  S000174\t"; grep -P "CACATG|CATGTG" $1 | wc -l
echo -ne "unknown         MYCCONSENSUSAT       CANNTG                         6  S000407\t"; grep -P "CA[ATCG]NTG|CAN[CGAT]TG" $1 | wc -l
echo -ne "unknown         NAPINMOTIFBN         TACACAT                        7  S000070\t"; grep -P "TACACAT|ATGTGTA" $1 | wc -l
echo -ne "unknown         NDEGMSAUR            CCATATGCCATGTCTCTCAATTGGTCCCAT 30 S000359\t"; grep -P "CCATATGCCATGTCTCTCAATTGGTCCCAT|ATGGGACCAATTGAGAGACATGGCATATGG" $1 | wc -l
echo -ne "unknown         NODCON1GM            AAAGAT                         6  S000461\t"; grep -P "AAAGAT|ATCTTT" $1 | wc -l
echo -ne "unknown         NODCON2GM            CTCTT                          5  S000462\t"; grep -P "CTCTT|AAGAG" $1 | wc -l
echo -ne "unknown         NONAMERATH4          AGATCGACG                      9  S000147\t"; grep -P "AGATCGACG|CGTCGATCT" $1 | wc -l
echo -ne "unknown         NONAMERMOTIFTAH3H4   CATCCAACG                      9  S000071\t"; grep -P "CATCCAACG|CGTTGGATG" $1 | wc -l
echo -ne "unknown         NRRBNEXTA            TAGTGGAT                       8  S000242\t"; grep -P "TAGTGGAT|ATCCACTA" $1 | wc -l
echo -ne "unknown         NTBBF1ARROLB         ACTTTA                         6  S000273\t"; grep -P "ACTTTA|TAAAGT" $1 | wc -l
echo -ne "unknown         O2F1BE2S1            TCCACGTCGA                     10 S000162\t"; grep -P "TCCACGTCGA|TCGACGTGGA" $1 | wc -l
echo -ne "unknown         O2F2BE2S1            GCCACCTCAT                     10 S000163\t"; grep -P "GCCACCTCAT|ATGAGGTGGC" $1 | wc -l
echo -ne "unknown         O2F3BE2S1            TCCACGTACT                     10 S000164\t"; grep -P "TCCACGTACT|AGTACGTGGA" $1 | wc -l
echo -ne "unknown         OBF5ATGST6           ATCTTATGTCATTGATGACGACCTCC     26 S000304\t"; grep -P "ATCTTATGTCATTGATGACGACCTCC|GGAGGTCGTCATCAATGACATAAGAT" $1 | wc -l
echo -ne "unknown         OBP1ATGST6           TACACTTTTGG                    11 S000305\t"; grep -P "TACACTTTTGG|CCAAAAGTGTA" $1 | wc -l
echo -ne "unknown         OCETYPEIIINTHISTONE  GATCCGCGNNNNNNNNNNNNNNACCAATCS 30 S000269\t"; grep -P "GATCCGCG[ATCG]NNNNNNNNNNNNNACCAATC[GC]|[GC]GATTGGTNNNNNNNNNNNNN[CGAT]CGCGGATC" $1 | wc -l
echo -ne "unknown         OCETYPEIINTHISTONE   TCACGCGGATC                    11 S000268\t"; grep -P "TCACGCGGATC|GATCCGCGTGA" $1 | wc -l
echo -ne "unknown         OCETYPEINTHISTONE    CCACGTCANCGATCCGCG             18 S000267\t"; grep -P "CCACGTCA[ATCG]CGATCCGCG|CGCGGATCG[CGAT]TGACGTGG" $1 | wc -l
echo -ne "unknown         OCSELEMENTAT         TGACGYAAGSRMTKACGYMM           20 S000158\t"; grep -P "TGACG[CT]AAG[GC][AG][AC]T[GT]ACGYMM|MMYCGT[AC]A[GT][CT][GC]CTT[AG]CGTCA" $1 | wc -l
echo -ne "unknown         OCSENHANMOTIFAT      ACGTAAGCGCTTACGT               16 S000074\t"; grep -P "ACGTAAGCGCTTACGT|ACGTAAGCGCTTACGT" $1 | wc -l
echo -ne "unknown         OCSGMGH24            CGGTTTACGTAATCTCTTACATCA       24 S000346\t"; grep -P "CGGTTTACGTAATCTCTTACATCA|TGATGTAAGAGATTACGTAAACCG" $1 | wc -l
echo -ne "unknown         OCSGMHSP26A          TGATGTAAGAGATTACGTAA           20 S000357\t"; grep -P "TGATGTAAGAGATTACGTAA|TTACGTAATCTCTTACATCA" $1 | wc -l
echo -ne "unknown         OCTAMERMOTIFTAH3H4   CGCGGATC                       8  S000076\t"; grep -P "CGCGGATC|GATCCGCG" $1 | wc -l
echo -ne "unknown         OCTAMOTIF2           CGCGGCAT                       8  S000116\t"; grep -P "CGCGGCAT|ATGCCGCG" $1 | wc -l
echo -ne "unknown         OPAQUE2ZM22Z         TCCACGTAGA                     10 S000017\t"; grep -P "TCCACGTAGA|TCTACGTGGA" $1 | wc -l
echo -ne "unknown         OPAQUE2ZMB32         GATGAYRTGG                     10 S000077\t"; grep -P "GATGA[CT][AG]TGG|CCA[CT][AG]TCATC" $1 | wc -l
echo -ne "unknown         OSE1ROOTNODULE       AAAGAT                         6  S000467\t"; grep -P "AAAGAT|ATCTTT" $1 | wc -l
echo -ne "unknown         OSE2ROOTNODULE       CTCTT                          5  S000468\t"; grep -P "CTCTT|AAGAG" $1 | wc -l
echo -ne "unknown         P1BS                 GNATATNC                       8  S000459\t"; grep -P "G[ATCG]ATATNC|GNATAT[CGAT]C" $1 | wc -l
echo -ne "unknown         PALBOXAPC            CCGTCC                         6  S000137\t"; grep -P "CCGTCC|GGACGG" $1 | wc -l
echo -ne "unknown         PALBOXLPC            YCYYACCWACC                    11 S000138\t"; grep -P "[CT]CYYACC[AT]ACC|GGT[AT]GGTYYG[AG]" $1 | wc -l
echo -ne "unknown         PALBOXPPC            YTYYMMCMAMCMMC                 14 S000136\t"; grep -P "[CT]TYY[AC]MCMAMCMMC|GMMGMTMGM[GT]YYA[AG]" $1 | wc -l
echo -ne "unknown         PALINDROMICCBOXGM    TGACGTCA                       8  S000255\t"; grep -P "TGACGTCA|TGACGTCA" $1 | wc -l
echo -ne "unknown         PASNTPARA            TTACGCAAGCAATGACATCT           20 S000336\t"; grep -P "TTACGCAAGCAATGACATCT|AGATGTCATTGCTTGCGTAA" $1 | wc -l
echo -ne "unknown         PE1ASPHYA3           GAAATAGCAAATGTTAAAAATA         22 S000196\t"; grep -P "GAAATAGCAAATGTTAAAAATA|TATTTTTAACATTTGCTATTTC" $1 | wc -l
echo -ne "unknown         PE2FNTRNR1A          ATTCGCGC                       8  S000455\t"; grep -P "ATTCGCGC|GCGCGAAT" $1 | wc -l
echo -ne "unknown         PE3ASPHYA3           CAGCTCCCATGGCTCTCCCATCCGCGCCGGT 31 S000197\t"; grep -P "CAGCTCCCATGGCTCTCCCATCCGCGCCGGT|ACCGGCGCGGATGGGAGAGCCATGGGAGCTG" $1 | wc -l
echo -ne "unknown         PIATGAPB             GTGATCAC                       8  S000381\t"; grep -P "GTGATCAC|GTGATCAC" $1 | wc -l
echo -ne "unknown         PIIATGAPB            TTGGTTTTGATCAAAACCAA           20 S000382\t"; grep -P "TTGGTTTTGATCAAAACCAA|TTGGTTTTGATCAAAACCAA" $1 | wc -l
echo -ne "unknown         POLASIG1             AATAAA                         6  S000080\t"; grep -P "AATAAA|TTTATT" $1 | wc -l
echo -ne "unknown         POLASIG2             AATTAAA                        7  S000081\t"; grep -P "AATTAAA|TTTAATT" $1 | wc -l
echo -ne "unknown         POLASIG3             AATAAT                         6  S000088\t"; grep -P "AATAAT|ATTATT" $1 | wc -l
echo -ne "unknown         POLLEN1LELAT52       AGAAA                          5  S000245\t"; grep -P "AGAAA|TTTCT" $1 | wc -l
echo -ne "unknown         POLLEN2LELAT52       TCCACCATA                      9  S000246\t"; grep -P "TCCACCATA|TATGGTGGA" $1 | wc -l
echo -ne "unknown         PR2GCNT              TAARAGCCGCC                    11 S000089\t"; grep -P "TAA[AG]AGCCGCC|GGCGGCT[CT]TTA" $1 | wc -l
echo -ne "unknown         PREATPRODH           ACTCAT                         6  S000450\t"; grep -P "ACTCAT|ATGAGT" $1 | wc -l
echo -ne "unknown         PRECONSCRHSP70A      SCGAYNRNNNNNNNNNNNNNNNHD       24 S000506\t"; grep -P "[GC]CGA[CT][ATCG][AG]NNNNNNNNNNNNNNN[ATC][GAT]|[ATC][GAT]NNNNNNNNNNNNNNN[CT][CGAT][AG]TCG[GC]" $1 | wc -l
echo -ne "unknown         PREMOTIFNPCABE       ACCGGCCCACTT                   12 S000230\t"; grep -P "ACCGGCCCACTT|AAGTGGGCCGGT" $1 | wc -l
echo -ne "unknown         PROLAMINBOX          CACATGTGTAAAGGT                15 S000091\t"; grep -P "CACATGTGTAAAGGT|ACCTTTACACATGTG" $1 | wc -l
echo -ne "unknown         PROLAMINBOXOSGLUB1   TGCAAAG                        7  S000354\t"; grep -P "TGCAAAG|CTTTGCA" $1 | wc -l
echo -ne "unknown         PROXBBNNAPA          CAAACACC                       8  S000263\t"; grep -P "CAAACACC|GGTGTTTG" $1 | wc -l
echo -ne "unknown         PSREGIONZMZM13       TCGGCCACTATTTCTACGGGCAGCCAGACAAA 32 S000253\t"; grep -P "TCGGCCACTATTTCTACGGGCAGCCAGACAAA|TTTGTCTGGCTGCCCGTAGAAATAGTGGCCGA" $1 | wc -l
echo -ne "unknown         PYRIMIDINEBOXHVEPB1  TTTTTTCC                       8  S000298\t"; grep -P "TTTTTTCC|GGAAAAAA" $1 | wc -l
echo -ne "unknown         PYRIMIDINEBOXOSRAMY1A CCTTTT                         6  S000259\t"; grep -P "CCTTTT|AAAAGG" $1 | wc -l
echo -ne "unknown         QARBNEXTA            AACGTGT                        7  S000244\t"; grep -P "AACGTGT|ACACGTT" $1 | wc -l
echo -ne "unknown         QELEMENTZMZM13       AGGTCA                         6  S000254\t"; grep -P "AGGTCA|TGACCT" $1 | wc -l
echo -ne "unknown         RAV1AAT              CAACA                          5  S000314\t"; grep -P "CAACA|TGTTG" $1 | wc -l
echo -ne "unknown         RAV1BAT              CACCTG                         6  S000315\t"; grep -P "CACCTG|CAGGTG" $1 | wc -l
echo -ne "unknown         RBCSBOX2PS           GTGTGGTTAATATG                 14 S000094\t"; grep -P "GTGTGGTTAATATG|CATATTAACCACAC" $1 | wc -l
echo -ne "unknown         RBCSBOX3PS           ATCATTTTCACT                   12 S000095\t"; grep -P "ATCATTTTCACT|AGTGAAAATGAT" $1 | wc -l
echo -ne "unknown         RBCSCONSENSUS        AATCCAA                        7  S000127\t"; grep -P "AATCCAA|TTGGATT" $1 | wc -l
echo -ne "unknown         RBCSGBOXPS           CACATGGCACT                    11 S000096\t"; grep -P "CACATGGCACT|AGTGCCATGTG" $1 | wc -l
echo -ne "unknown         RBENTGA3             TCCAACTTGGA                    11 S000358\t"; grep -P "TCCAACTTGGA|TCCAAGTTGGA" $1 | wc -l
echo -ne "unknown         RE1ASPHYA3           CATGGGCGCGG                    11 S000195\t"; grep -P "CATGGGCGCGG|CCGCGCCCATG" $1 | wc -l
echo -ne "unknown         REALPHALGLHCB21      AACCAA                         6  S000362\t"; grep -P "AACCAA|TTGGTT" $1 | wc -l
echo -ne "unknown         REBETALGLHCB21       CGGATA                         6  S000363\t"; grep -P "CGGATA|TATCCG" $1 | wc -l
echo -ne "unknown         REGION1OSOSEM        CGGCGGCCTCGCCACG               16 S000300\t"; grep -P "CGGCGGCCTCGCCACG|CGTGGCGAGGCCGCCG" $1 | wc -l
echo -ne "unknown         RGATAOS              CAGAAGATA                      9  S000191\t"; grep -P "CAGAAGATA|TATCTTCTG" $1 | wc -l
echo -ne "unknown         RHERPATEXPA7         KCACGW                         6  S000512\t"; grep -P "[GT]CACG[AT]|[AT]CGTG[AC]" $1 | wc -l
echo -ne "unknown         RNFG1OS              GATCATCGATC                    11 S000188\t"; grep -P "GATCATCGATC|GATCGATGATC" $1 | wc -l
echo -ne "unknown         RNFG2OS              CCAGTGTGCCCCTGG                15 S000189\t"; grep -P "CCAGTGTGCCCCTGG|CCAGGGGCACACTGG" $1 | wc -l
echo -ne "unknown         ROOTMOTIFTAPOX1      ATATT                          5  S000098\t"; grep -P "ATATT|AATAT" $1 | wc -l
echo -ne "unknown         RSEPVGRP1            CAACTTTCATAT                   12 S000099\t"; grep -P "CAACTTTCATAT|ATATGAAAGTTG" $1 | wc -l
echo -ne "unknown         RSEPVGRP18           CATCCAACTTTCATATCCATGTGCTT     26 S000289\t"; grep -P "CATCCAACTTTCATATCCATGTGCTT|AAGCACATGGATATGAAAGTTGGATG" $1 | wc -l
echo -ne "unknown         RSRBNEXTA            CAAACTCGTATATCCAT              17 S000243\t"; grep -P "CAAACTCGTATATCCAT|ATGGATATACGAGTTTG" $1 | wc -l
echo -ne "unknown         RYREPEAT4            TCCATGCATGCAC                  13 S000010\t"; grep -P "TCCATGCATGCAC|GTGCATGCATGGA" $1 | wc -l
echo -ne "unknown         RYREPEATBNNAPA       CATGCA                         6  S000264\t"; grep -P "CATGCA|TGCATG" $1 | wc -l
echo -ne "unknown         RYREPEATGMGY2        CATGCAT                        7  S000105\t"; grep -P "CATGCAT|ATGCATG" $1 | wc -l
echo -ne "unknown         RYREPEATLEGUMINBOX   CATGCAY                        7  S000100\t"; grep -P "CATGCA[CT]|[AG]TGCATG" $1 | wc -l
echo -ne "unknown         RYREPEATVFLEB4       CATGCATG                       8  S000102\t"; grep -P "CATGCATG|CATGCATG" $1 | wc -l
echo -ne "unknown         S1FBOXSORPS1L21      ATGGTA                         6  S000223\t"; grep -P "ATGGTA|TACCAT" $1 | wc -l
echo -ne "unknown         S1FSORPL21           ATGGTATT                       8  S000215\t"; grep -P "ATGGTATT|AATACCAT" $1 | wc -l
echo -ne "unknown         S2FSORPL21           CCATACATT                      9  S000166\t"; grep -P "CCATACATT|AATGTATGG" $1 | wc -l
echo -ne "unknown         SARECAMV             CTGACGTAAGGGATGACGCAC          21 S000156\t"; grep -P "CTGACGTAAGGGATGACGCAC|GTGCGTCATCCCTTACGTCAG" $1 | wc -l
echo -ne "unknown         SB1NPABC1            CACTAACACAAAGTAA               16 S000435\t"; grep -P "CACTAACACAAAGTAA|TTACTTTGTGTTAGTG" $1 | wc -l
echo -ne "unknown         SB3NPABC1            TTATGAACAGTAATT                15 S000434\t"; grep -P "TTATGAACAGTAATT|AATTACTGTTCATAA" $1 | wc -l
echo -ne "unknown         SBOXATRBCS           CACCTCCA                       8  S000500\t"; grep -P "CACCTCCA|TGGAGGTG" $1 | wc -l
echo -ne "unknown         SE1PVGRP18           ATAATGGGCCACACTGTGGGGCAT       24 S000288\t"; grep -P "ATAATGGGCCACACTGTGGGGCAT|ATGCCCCACAGTGTGGCCCATTAT" $1 | wc -l
echo -ne "unknown         SE2PVGRP1            TTNNNGTAGCTAGTGTATTTGTAT       24 S000101\t"; grep -P "TT[ATCG]NNGTAGCTAGTGTATTTGTAT|ATACAAATACACTAGCTACNN[CGAT]AA" $1 | wc -l
echo -ne "unknown         SEBFCONSSTPR10A      YTGTCWC                        7  S000391\t"; grep -P "[CT]TGTC[AT]C|G[AT]GACA[AG]" $1 | wc -l
echo -ne "unknown         SEF1MOTIF            ATATTTAWW                      9  S000006\t"; grep -P "ATATTTA[AT]W|W[AT]TAAATAT" $1 | wc -l
echo -ne "unknown         SEF3MOTIFGM          AACCCA                         6  S000115\t"; grep -P "AACCCA|TGGGTT" $1 | wc -l
echo -ne "unknown         SEF4MOTIFGM7S        RTTTTTR                        7  S000103\t"; grep -P "[AG]TTTTTR|RAAAAA[CT]" $1 | wc -l
echo -ne "unknown         SGBFGMGMAUX28        TCCACGTGTC                     10 S000287\t"; grep -P "TCCACGTGTC|GACACGTGGA" $1 | wc -l
echo -ne "unknown         SITE1SORPS1          TCATGGTAACAATT                 14 S000211\t"; grep -P "TCATGGTAACAATT|AATTGTTACCATGA" $1 | wc -l
echo -ne "unknown         SITE3SORPS1          AGTTAGTTAAAAGA                 14 S000212\t"; grep -P "AGTTAGTTAAAAGA|TCTTTTAACTAACT" $1 | wc -l
echo -ne "unknown         SITEIIAOSPCNA        TGGGCCCGT                      9  S000216\t"; grep -P "TGGGCCCGT|ACGGGCCCA" $1 | wc -l
echo -ne "unknown         SITEIIATCYTC         TGGGCY                         6  S000474\t"; grep -P "TGGGC[CT]|[AG]GCCCA" $1 | wc -l
echo -ne "unknown         SITEIIBOSPCNA        TGGTCCCAC                      9  S000217\t"; grep -P "TGGTCCCAC|GTGGGACCA" $1 | wc -l
echo -ne "unknown         SITEIOSPCNA          CCAGGTGG                       8  S000224\t"; grep -P "CCAGGTGG|CCACCTGG" $1 | wc -l
echo -ne "unknown         SORLIP1AT            GCCAC                          5  S000482\t"; grep -P "GCCAC|GTGGC" $1 | wc -l
echo -ne "unknown         SORLIP2AT            GGGCC                          5  S000483\t"; grep -P "GGGCC|GGCCC" $1 | wc -l
echo -ne "unknown         SORLIP3AT            CTCAAGTGA                      9  S000484\t"; grep -P "CTCAAGTGA|TCACTTGAG" $1 | wc -l
echo -ne "unknown         SORLIP4AT            GTATGATGG                      9  S000485\t"; grep -P "GTATGATGG|CCATCATAC" $1 | wc -l
echo -ne "unknown         SORLIP5AT            GAGTGAG                        7  S000486\t"; grep -P "GAGTGAG|CTCACTC" $1 | wc -l
echo -ne "unknown         SORLREP2AT           ATAAAACGT                      9  S000487\t"; grep -P "ATAAAACGT|ACGTTTTAT" $1 | wc -l
echo -ne "unknown         SORLREP3AT           TGTATATAT                      9  S000488\t"; grep -P "TGTATATAT|ATATATACA" $1 | wc -l
echo -ne "unknown         SORLREP4AT           CTCCTAATT                      9  S000489\t"; grep -P "CTCCTAATT|AATTAGGAG" $1 | wc -l
echo -ne "unknown         SORLREP5AT           TTGCATGACT                     10 S000490\t"; grep -P "TTGCATGACT|AGTCATGCAA" $1 | wc -l
echo -ne "unknown         SP8BFIBSP8AIB        ACTGTGTA                       8  S000183\t"; grep -P "ACTGTGTA|TACACAGT" $1 | wc -l
echo -ne "unknown         SP8BFIBSP8BIB        TACTATT                        7  S000184\t"; grep -P "TACTATT|AATAGTA" $1 | wc -l
echo -ne "unknown         SPHCOREZMC1          TCCATGCAT                      9  S000154\t"; grep -P "TCCATGCAT|ATGCATGGA" $1 | wc -l
echo -ne "unknown         SPHZMC1              CGTCCATGCAT                    11 S000293\t"; grep -P "CGTCCATGCAT|ATGCATGGACG" $1 | wc -l
echo -ne "unknown         SREATMSD             TTATCC                         6  S000470\t"; grep -P "TTATCC|GGATAA" $1 | wc -l
echo -ne "unknown         SRENTTTO1            TGGTAGGTGAGAT                  13 S000271\t"; grep -P "TGGTAGGTGAGAT|ATCTCACCTACCA" $1 | wc -l
echo -ne "unknown         SURE1STPAT21         AATAGAAAA                      9  S000186\t"; grep -P "AATAGAAAA|TTTTCTATT" $1 | wc -l
echo -ne "unknown         SURE2STPAT21         AATACTAAT                      9  S000185\t"; grep -P "AATACTAAT|ATTAGTATT" $1 | wc -l
echo -ne "unknown         SUREAHVISO1          AAAACTAAGAAAGACCGATGGAAAA      25 S000441\t"; grep -P "AAAACTAAGAAAGACCGATGGAAAA|TTTTCCATCGGTCTTTCTTAGTTTT" $1 | wc -l
echo -ne "unknown         SURECOREATSULTR11    GAGAC                          5  S000499\t"; grep -P "GAGAC|GTCTC" $1 | wc -l
echo -ne "unknown         SV40COREENHAN        GTGGWWHG                       8  S000123\t"; grep -P "GTGG[AT]W[ATC]G|C[GAT]W[AT]CCAC" $1 | wc -l
echo -ne "unknown         T/GBOXATPIN2         AACGTG                         6  S000458\t"; grep -P "AACGTG|CACGTT" $1 | wc -l
echo -ne "unknown         TAAAGSTKST1          TAAAG                          5  S000387\t"; grep -P "TAAAG|CTTTA" $1 | wc -l
echo -ne "unknown         TACBBFNTEAS4         ACTCTACAGTACTC                 14 S000257\t"; grep -P "ACTCTACAGTACTC|GAGTACTGTAGAGT" $1 | wc -l
echo -ne "unknown         TATABOX1             CTATAAATAC                     10 S000108\t"; grep -P "CTATAAATAC|GTATTTATAG" $1 | wc -l
echo -ne "unknown         TATABOX2             TATAAAT                        7  S000109\t"; grep -P "TATAAAT|ATTTATA" $1 | wc -l
echo -ne "unknown         TATABOX3             TATTAAT                        7  S000110\t"; grep -P "TATTAAT|ATTAATA" $1 | wc -l
echo -ne "unknown         TATABOX4             TATATAA                        7  S000111\t"; grep -P "TATATAA|TTATATA" $1 | wc -l
echo -ne "unknown         TATABOX5             TTATTT                         6  S000203\t"; grep -P "TTATTT|AAATAA" $1 | wc -l
echo -ne "unknown         TATABOXOSPAL         TATTTAA                        7  S000400\t"; grep -P "TATTTAA|TTAAATA" $1 | wc -l
echo -ne "unknown         TATAPVTRNALEU        TTTATATA                       8  S000340\t"; grep -P "TTTATATA|TATATAAA" $1 | wc -l
echo -ne "unknown         TATCCACHVAL21        TATCCAC                        7  S000416\t"; grep -P "TATCCAC|GTGGATA" $1 | wc -l
echo -ne "unknown         TATCCAOSAMY          TATCCA                         6  S000403\t"; grep -P "TATCCA|TGGATA" $1 | wc -l
echo -ne "unknown         TATCCAYMOTIFOSRAMY3D TATCCAY                        7  S000256\t"; grep -P "TATCCA[CT]|[AG]TGGATA" $1 | wc -l
echo -ne "unknown         TBOXATGAPB           ACTTTG                         6  S000383\t"; grep -P "ACTTTG|CAAAGT" $1 | wc -l
echo -ne "unknown         TCA1MOTIF            TCATCTTCTT                     10 S000159\t"; grep -P "TCATCTTCTT|AAGAAGATGA" $1 | wc -l
echo -ne "unknown         TDBA12NTCHN50        TGACTTTCTGAC                   12 S000266\t"; grep -P "TGACTTTCTGAC|GTCAGAAAGTCA" $1 | wc -l
echo -ne "unknown         TE2F2NTPCNA          ATTCCCGC                       8  S000397\t"; grep -P "ATTCCCGC|GCGGGAAT" $1 | wc -l
echo -ne "unknown         TEF1BOXATA1          ACAGGGGCATAATGGTAATTTAAA       24 S000311\t"; grep -P "ACAGGGGCATAATGGTAATTTAAA|TTTAAATTACCATTATGCCCCTGT" $1 | wc -l
echo -ne "unknown         TEFBOXATEEF1AA1      AGGGGCATAATGGTAA               16 S000309\t"; grep -P "AGGGGCATAATGGTAA|TTACCATTATGCCCCT" $1 | wc -l
echo -ne "unknown         TELOBOXATEEF1AA1     AAACCCTAA                      9  S000308\t"; grep -P "AAACCCTAA|TTAGGGTTT" $1 | wc -l
echo -ne "unknown         TGA1ANTPR1A          CGTCATCGAGATGACG               16 S000247\t"; grep -P "CGTCATCGAGATGACG|CGTCATCTCGATGACG" $1 | wc -l
echo -ne "unknown         TGACGTVMAMY          TGACGT                         6  S000377\t"; grep -P "TGACGT|ACGTCA" $1 | wc -l
echo -ne "unknown         TGTCACACMCUCUMISIN   TGTCACA                        7  S000422\t"; grep -P "TGTCACA|TGTGACA" $1 | wc -l
echo -ne "unknown         TL1ATSAR             CTGAAGAAGAA                    11 S000473\t"; grep -P "CTGAAGAAGAA|TTCTTCTTCAG" $1 | wc -l
echo -ne "unknown         TOPOISOM             GTNWAYATTNATNNG                15 S000112\t"; grep -P "GT[ATCG][AT]A[CT]ATTNATNNG|CNNATNAAT[AG]T[AT][CGAT]AC" $1 | wc -l
echo -ne "unknown         TRANSINITDICOTS      AMNAUGGC                       8  S000201\t"; grep -P "A[AC][ATCG]AUGGC|GCCUT[CGAT][GT]T" $1 | wc -l
echo -ne "unknown         TRANSINITMONOCOTS    RMNAUGGC                       8  S000202\t"; grep -P "[AG][AC][ATCG]AUGGC|GCCUT[CGAT][GT][CT]" $1 | wc -l
echo -ne "unknown         TRANSTART            TAAACAATGGCT                   12 S000113\t"; grep -P "TAAACAATGGCT|AGCCATTGTTTA" $1 | wc -l
echo -ne "unknown         UP1ATMSD             GGCCCAWWW                      9  S000471\t"; grep -P "GGCCCA[AT]WW|WW[AT]TGGGCC" $1 | wc -l
echo -ne "unknown         UP2ATMSD             AAACCCTA                       8  S000472\t"; grep -P "AAACCCTA|TAGGGTTT" $1 | wc -l
echo -ne "unknown         UPRE1AT              ATTGGTCCACG                    11 S000428\t"; grep -P "ATTGGTCCACG|CGTGGACCAAT" $1 | wc -l
echo -ne "unknown         UPRE2AT              CCACGTCATC                     10 S000429\t"; grep -P "CCACGTCATC|GATGACGTGG" $1 | wc -l
echo -ne "unknown         UPRMOTIFIAT          CCACGTCA                       8  S000425\t"; grep -P "CCACGTCA|TGACGTGG" $1 | wc -l
echo -ne "unknown         UPRMOTIFIIAT         CCNNNNNNNNNNNNCCACG            19 S000426\t"; grep -P "CC[ATCG]NNNNNNNNNNNCCACG|CGTGGNNNNNNNNNNN[CGAT]GG" $1 | wc -l
echo -ne "unknown         VOZATVPP             GCGTNNNNNNNACGC                15 S000456\t"; grep -P "GCGT[ATCG]NNNNNNACGC|GCGTNNNNNN[CGAT]ACGC" $1 | wc -l
echo -ne "unknown         VSF1PVGRP18          GCTCCGTTG                      9  S000249\t"; grep -P "GCTCCGTTG|CAACGGAGC" $1 | wc -l
echo -ne "unknown         WARBNEXTA            GTACGTGTTATAAAACGTGT           20 S000241\t"; grep -P "GTACGTGTTATAAAACGTGT|ACACGTTTTATAACACGTAC" $1 | wc -l
echo -ne "unknown         WBBOXPCWRKY1         TTTGACY                        7  S000310\t"; grep -P "TTTGAC[CT]|[AG]GTCAAA" $1 | wc -l
echo -ne "unknown         WBOXATNPR1           TTGAC                          5  S000390\t"; grep -P "TTGAC|GTCAA" $1 | wc -l
echo -ne "unknown         WBOXGACAD1A          AGTCAAAATTGACC                 14 S000448\t"; grep -P "AGTCAAAATTGACC|GGTCAATTTTGACT" $1 | wc -l
echo -ne "unknown         WBOXHVISO1           TGACT                          5  S000442\t"; grep -P "TGACT|AGTCA" $1 | wc -l
echo -ne "unknown         WBOXNTCHN48          CTGACY                         6  S000508\t"; grep -P "CTGAC[CT]|[AG]GTCAG" $1 | wc -l
echo -ne "unknown         WBOXNTERF3           TGACY                          5  S000457\t"; grep -P "TGAC[CT]|[AG]GTCA" $1 | wc -l
echo -ne "unknown         WINPSTPIIIK          AAGCGTAAGT                     10 S000495\t"; grep -P "AAGCGTAAGT|ACTTACGCTT" $1 | wc -l
echo -ne "unknown         WRECSAA01            AAWGTATCSA                     10 S000496\t"; grep -P "AA[AT]GTATC[GC]A|T[GC]GATAC[AT]TT" $1 | wc -l
echo -ne "unknown         WRKY71OS             TGAC                           4  S000447\t"; grep -P "TGAC|GTCA" $1 | wc -l
echo -ne "unknown         WUSATAg              TTAATGG                        7  S000433\t"; grep -P "TTAATGG|CCATTAA" $1 | wc -l
echo -ne "unknown         XYLAT                ACAAAGAA                       8  S000510\t"; grep -P "ACAAAGAA|TTCTTTGT" $1 | wc -l
echo -ne "unknown         YREGIONNTPRB1B       TGTGACATTGAAATTCTTTGACTTTA     26 S000365\t"; grep -P "TGTGACATTGAAATTCTTTGACTTTA|TAAAGTCAAAGAATTTCAATGTCACA" $1 | wc -l
echo -ne "unknown         ZDNAFORMINGATCAB1    ATACGTGT                       8  S000321\t"; grep -P "ATACGTGT|ACACGTAT" $1 | wc -l
